// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:37817d17-8481-4be6-8f56-c6cf233e3003',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'rnauthtest-hosting-mobilehub-1534563465',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dabsyrplo2sin.cloudfront.net',
    'aws_mobile_analytics_app_id': '292c8d28907d45919dafa72e3ac86788',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '0ae53bf9-f766-44ee-88a2-b5b333452bef',
    'aws_project_name': 'RNAuthTest1',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'rnauthtest-mobilehub-1534563465',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_exVATSR3D',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '7cvnhrsmhnpgkg2p4ug7tf1oaa',
}

export default awsmobile;
